### ISSUE TITLE
Core.lua:202: table index is nil

### ISSUE THREAD

**Issue by tordenflesk** [Meivyn/AdventureGuideLockouts#10]
3x AdventureGuideLockouts\Core.lua:202: table index is nil
AdventureGuideLockouts\Core.lua:202: in function `UpdateSavedInstances'
AdventureGuideLockouts\Core.lua:385: in function <AdventureGuideLockouts\Core.lua:377>

Locals:
self = <table> {
 worldBosses = <table> {
 }
 UpdateStatusFramePosition = <function> defined @AdventureGuideLockouts\Core.lua:285
 UpdateSavedInstances = <function> defined @AdventureGuideLockouts\Core.lua:131
 isDarkshoreAvailable = false
 isStromgardeAvailable = true
 instances = <table> {
 }
 GetSavedWorldBossEncounterInfo = <function> defined @AdventureGuideLockouts\Core.lua:119
 instancesLockouts = <table> {
 }
 UpdateInstanceStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:328
 RequestWarfrontInfo = <function> defined @AdventureGuideLockouts\Core.lua:50
 CreateStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:220
 GetSavedWorldBossInfo = <function> defined @AdventureGuideLockouts\Core.lua:89
 eventFrame = <unnamed> {
 }
 UpdateFrames = <function> defined @AdventureGuideLockouts\Core.lua:360
}
savedInstances = 3
savedWorldBosses = 5
instanceName = "The Eternal Palace"
instanceID = nil
instanceReset = 131851
instanceDifficulty = 17
locked = true
extended = false
instanceIDMostSig = 524550145
isRaid = true
maxPlayers = 30
difficultyName = "Looking For Raid"
numEncounters = 0
numCompleted = 0
difficulty = 1
playerFaction = "Alliance"
(for index) = 1
(for limit) = 8
(for step) = 1
instanceIndex = 1
encounters = <table> {
}
encounterIndex = 1
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
GetNumSavedInstances = <function> defined =[C]:-1
UnitFactionGroup = <function> defined =[C]:-1
GetSavedInstanceInfo = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
GetSavedInstanceChatLink = <function> defined =[C]:-1
GetDifficultyInfo = <function> defined =[C]:-1
GetSavedInstanceEncounterInfo = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
C_TaskQuest_GetQuestTimeLeftMinutes = <function> defined =[C]:-1

**Comment by Meivyn** [comment]
Hello, can you let me know what you were doing at the time of the error?

**Comment by tordenflesk** [comment]
Iirc, opened the guide while in a normal-mode raid.

-Espen

**Comment by Meivyn** [comment]
After reloading, do you get that error again? If so, please open ``Core.lua`` and replace line 145 
```lua
      instanceID = self.instances[tonumber(GetSavedInstanceChatLink(instanceIndex):match(":(%d+)"))]
```
With
```lua
      local instanceLink = GetSavedInstanceChatLink(instanceIndex)
      local instanceLinkID = tonumber(instanceLink:match(":(%d+)"))
      instanceID = self.instances[instanceLinkID]
```
Then save and do a ``/reload``, and show me the error again please.

**Comment by VIKINGYFY** [comment]
> After reloading, do you get that error again? If so, please open `Core.lua` and replace line 145
> 
> ```lua
>       instanceID = self.instances[tonumber(GetSavedInstanceChatLink(instanceIndex):match(":(%d+)"))]
> ```
> 
> With
> 
> ```lua
>       local instanceLink = GetSavedInstanceChatLink(instanceIndex)
>       local instanceLinkID = tonumber(instanceLink:match(":(%d+)"))
>       instanceID = self.instances[instanceLinkID]
> ```
> 
> Then save and do a `/reload`, and show me the error again please.

Same problem.
The Stonecore(instanceID = 725) too.

I think I know why, instanceID is wrong in Instances.lua.
like Stonecore, true instanceID is 725, but 752 in your Instances.lua.

**Comment by Meivyn** [comment]
Yeah this one is probably a typo, thanks for pointing it out, but it shouldn't happens with The Eternal Palace. Please post your error again so I can see the values used by the variables after my edits.

**Comment by tordenflesk** [comment]
Another one, during a HC Island:
> 1x AdventureGuideLockouts\Core.lua:202: table index is nil
>
> AdventureGuideLockouts\Core.lua:202: in function `UpdateSavedInstances'
> AdventureGuideLockouts\Core.lua:385: in function <AdventureGuideLockouts\Core.lua:377>
> 
> Locals:
> self = <table> {
>  worldBosses = <table> {
>  }
>  UpdateStatusFramePosition = <function> defined @AdventureGuideLockouts\Core.lua:285
>  UpdateSavedInstances = <function> defined @AdventureGuideLockouts\Core.lua:131
>  isDarkshoreAvailable = false
>  isStromgardeAvailable = true
>  instances = <table> {
>  }
>  GetSavedWorldBossEncounterInfo = <function> defined @AdventureGuideLockouts\Core.lua:119
>  instancesLockouts = <table> {
>  }
>  UpdateInstanceStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:328
>  RequestWarfrontInfo = <function> defined @AdventureGuideLockouts\Core.lua:50
>  CreateStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:220
>  GetSavedWorldBossInfo = <function> defined @AdventureGuideLockouts\Core.lua:89
>  eventFrame = <unnamed> {
>  }
>  UpdateFrames = <function> defined @AdventureGuideLockouts\Core.lua:360
> }
> savedInstances = 4
> savedWorldBosses = 5
> instanceName = "The Eternal Palace"
> instanceID = nil
> instanceReset = 570578
> instanceDifficulty = 17
> locked = true
> extended = false
> instanceIDMostSig = 524550145
> isRaid = true
> maxPlayers = 30
> difficultyName = "Looking For Raid"
> numEncounters = 0
> numCompleted = 0
> difficulty = 1
> playerFaction = "Alliance"
> (for index) = 1
> (for limit) = 9
> (for step) = 1
> instanceIndex = 1
> encounters = <table> {
> }
> encounterIndex = 1
> (*temporary) = <table> {
> }
> (*temporary) = <table> {
> }
> (*temporary) = false
> (*temporary) = false
> (*temporary) = false
> (*temporary) = false
> (*temporary) = nil
> (*temporary) = true
> (*temporary) = nil
> (*temporary) = 1
> (*temporary) = 1
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "table index is nil"
> GetNumSavedInstances = <function> defined =[C]:-1
> UnitFactionGroup = <function> defined =[C]:-1
> GetSavedInstanceInfo = <function> defined =[C]:-1
> tonumber = <function> defined =[C]:-1
> GetSavedInstanceChatLink = <function> defined =[C]:-1
> GetDifficultyInfo = <function> defined =[C]:-1
> GetSavedInstanceEncounterInfo = <function> defined =[C]:-1
> tinsert = <function> defined =[C]:-1
> C_TaskQuest_GetQuestTimeLeftMinutes = <function> defined =[C]:-1

**Comment by Meivyn** [comment]
This is another issue with The Eternal Palace in LFR mode. Please right-click [this file](https://gist.githubusercontent.com/Meivyn/c034136b1cd8d78d8c2c7160113d9306/raw/8025cfee03862a25e045a52edec1d95c8fc79635/Core.lua) then save as and replace the original ``Core.lua`` in ``World of Warcraft/_retail_/Interface/AddOns/AdventureGuideLockouts`` by this one. 

Relaunch WoW then show me the error again. I can't help you if you don't provide me more information with the edits I posted above.

**Comment by Meivyn** [comment]
Are you still having this issue? I'm waiting to fix it to push the release.

**Comment by VIKINGYFY** [comment]
> Are you still having this issue? I'm waiting to fix it to push the release.

emmm,its should be OK.

**Comment by tordenflesk** [comment]
Just zoned into "the circle of starts" LFR, first boss:

1x AdventureGuideLockouts\Core.lua:204: table index is nil
AdventureGuideLockouts\Core.lua:204: in function `UpdateSavedInstances'
AdventureGuideLockouts\Core.lua:387: in function <AdventureGuideLockouts\Core.lua:379>

Locals:
self = <table> {
 worldBosses = <table> {
 }
 UpdateStatusFramePosition = <function> defined @AdventureGuideLockouts\Core.lua:287
 UpdateSavedInstances = <function> defined @AdventureGuideLockouts\Core.lua:131
 isDarkshoreAvailable = true
 isStromgardeAvailable = false
 instances = <table> {
 }
 GetSavedWorldBossEncounterInfo = <function> defined @AdventureGuideLockouts\Core.lua:119
 instancesLockouts = <table> {
 }
 UpdateInstanceStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:330
 RequestWarfrontInfo = <function> defined @AdventureGuideLockouts\Core.lua:50
 CreateStatusFrame = <function> defined @AdventureGuideLockouts\Core.lua:222
 GetSavedWorldBossInfo = <function> defined @AdventureGuideLockouts\Core.lua:89
 eventFrame = <unnamed> {
 }
 UpdateFrames = <function> defined @AdventureGuideLockouts\Core.lua:362
}
savedInstances = 4
savedWorldBosses = 5
instanceName = "The Eternal Palace"
instanceID = nil
instanceReset = 299050
instanceDifficulty = 17
locked = true
extended = false
instanceIDMostSig = 524550145
isRaid = true
maxPlayers = 30
difficultyName = "Looking For Raid"
numEncounters = 0
numCompleted = 0
difficulty = 1
playerFaction = "Alliance"
(for index) = 1
(for limit) = 9
(for step) = 1
instanceIndex = 1
encounters = <table> {
}
encounterIndex = 1
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "Looking For Raid"
(*temporary) = "raid"
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = false
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
GetNumSavedInstances = <function> defined =[C]:-1
UnitFactionGroup = <function> defined =[C]:-1
GetSavedInstanceInfo = <function> defined =[C]:-1
GetSavedInstanceChatLink = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
GetDifficultyInfo = <function> defined =[C]:-1
GetSavedInstanceEncounterInfo = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
C_TaskQuest_GetQuestTimeLeftMinutes = <function> defined =[C]:-1

**Comment by Meivyn** [comment]
https://github.com/Meivyn/AdventureGuideLockouts/issues/10#issuecomment-521475032

I can't do more if you don't do this.

**Comment by VIKINGYFY** [comment]
> [#10 (comment)](https://github.com/Meivyn/AdventureGuideLockouts/issues/10#issuecomment-521475032)
> 
> I can't do more if you don't do this.

i test The Eternal Palace afternoon, its OK, you can push the release.

**Comment by Meivyn** [comment]
Closing the issue as I don't have any news from you, and sadly you don't help me to fix it.

**Comment by Meivyn** [comment]
I think you only have a too old version. This is why ``instanceID`` is ``nil`` as it's not present in ``Instances.lua``. I don't see any other case when this can happen. Anyway, be sure to update.
