### ISSUE TITLE
AdventureGuideLockouts DEBUG

### ISSUE THREAD

**Issue by Childishforlife** [Meivyn/AdventureGuideLockouts#18]
Hello!

Was doing vigilant guardian, and we killed the boss but then wiped. it says we wiped at 0.0%, but at the same time, we are somehow locked to the instance.

https://i.gyazo.com/3dfa900c51f5d6979e90aa40aac0cb5a.png

https://www.warcraftlogs.com/reports/a:7HQyGP6vcYqMWZDL#fight=9

https://www.youtube.com/watch?v=4v4dnGvjE9I

**Comment by Meivyn** [comment]
While this does complement really well my add-on, this isn't part of it, this is a base game feature that was added a while back already... Can't remember when though, I think it was in Shadowlands' beta.

![image](https://user-images.githubusercontent.com/793322/156723668-d3bf1084-859f-404c-b09d-9e84fece65a7.png)

As for your issue, it should be solved if you update the add-on to its latest version.
And... sorry for your kill, lol, I would probably have laughed if I were you.

**Comment by Childishforlife** [comment]
Hi there,

Thanks I didn't realize it was due to being out dated, I just updated it!

Yeah its brutal, no loot, doesn't count towards great vault, but we are locked. Brutal!
