### ISSUE TITLE
Issue upon login in Zereth Mortis

### ISSUE THREAD

**Issue by mjch05** [Meivyn/AdventureGuideLockouts#19]
I receive this error after I log in with my character. He previosly loged out while standing in Zereth Mortis.

AdventureGuideLookouts ERROR: instancelD is nil. Please report following values at https://github.com/Meivyn/AdventureGuideLockouts/issues 
AdventureGuideLockouts DEBUG: 
instanceMatch="2481", 
instanceLink="Jcffff8000|Hinstancelock:Player-1379-0AB5BC68:2481:14:1211|h[Sepulcher of the First Ones]|h|r"

**Comment by Meivyn** [comment]
That should be solved if you update to latest version.

**Comment by mjch05** [comment]
Yes, it seems that WowUp app was not providing the latest version.
I downloaded it manually from Curse and it is fine now, thanks!
