### ISSUE TITLE
Update for 10.0 ?

### ISSUE THREAD

**Issue by tatatada** [Meivyn/AdventureGuideLockouts#20]
will u update it for dragonflight ?

**Comment by Meivyn** [comment]
Yes, please give me time to figure out the best way to handle Blizzard's dumbness.

**Comment by Goten87** [comment]
i will like a update to miss the addon :(

**Comment by Grail-Lin** [comment]
excuse me.
I would like to update Instances.lua
but I don't know which value should I fill up for those instances.
May I know what is the value stand for? Thanks
----------------------------
  [2451] = , -- Uldaman: Legacy of Tyr
  [2515] = , -- The Azure Vault 
  [2516] = , -- The Nokhud Offensive
  [2519] = , -- Neltharus
  [2520] = , -- Brackenhide Hollow
  [2521] = , -- Ruby Life Pools
  [2526] = , -- Algeth'ar Academy
  [2527] = , -- Halls of Infusion
  [2522] =  -- Vault of the Incarnates

**Comment by Meivyn** [comment]
This wouldn't be enough to make it work. I am currently working on it, and I will try to push the update soon. That hardcoded stuff is also going to be removed. This simply associates the EncounterJournal `instanceID` to the actual `instanceID` of the lockouts, as they aren't the same. But I found a better way to handle this.

**Comment by Grail-Lin** [comment]
THANKS!!!
Sorry to bother you.
