### ISSUE TITLE
InstanceID is nil error

### ISSUE THREAD

**Issue by Glasse** [Meivyn/AdventureGuideLockouts#21]
AdventureGuideLockouts ERROR: instanceID is nil. Please report following values at https://github.com/Meivyn/AdventureGuideLockouts/issues
AdventureGuideLockouts DEBUG:
instanceLink="|cffff8000|Hinstancelock:Player-113-0A26EABE:2451:23:31|h[Uldaman: Legacy of Tyr]|h|r",
addonVersion="1.4.2",
instanceMatch="2451"

**Comment by Goten87** [comment]
i also have one for ya
```lua
AdventureGuideLockouts DEBUG:
instanceLink="|cffff8000|Hinstancelock:Player-3702-089CCC5E:2520:23:15|h[Brackenhide Hollow]|h|r",
addonVersion="1.4.2",
instanceMatch="2520"
```

**Comment by Meivyn** [comment]
That is normal and is going to happen until I update the add-on for Dragonflight. It isn't yet.
