### ISSUE TITLE
attempt to index field 'instanceLockouts' (a nil value)

### ISSUE THREAD

**Issue by yoshimo** [Meivyn/AdventureGuideLockouts#22]
30x ...ns/AdventureGuideLockouts/AdventureGuideLockouts.lua:341: attempt to index field 'instanceLockouts' (a nil value)
[string "@AdventureGuideLockouts/AdventureGuideLockouts.lua"]:341: in function `UpdateInstanceStatusFrame'
[string "@AdventureGuideLockouts/AdventureGuideLockouts.lua"]:419: in function <...ns/AdventureGuideLockouts/AdventureGuideLockouts.lua:414>
[string "=[C]"]: in function `SetUpdateLocked'
[string "@SharedXML/Scroll/ScrollBox.lua"]:668: in function `Update'
[string "@SharedXML/Scroll/ScrollBox.lua"]:163: in function `FullUpdateInternal'
[string "@SharedXML/Scroll/ScrollBox.lua"]:635: in function `FullUpdateInternal'
[string "@SharedXML/Scroll/ScrollBox.lua"]:117: in function `FullUpdate'
[string "@SharedXML/Scroll/ScrollBox.lua"]:609: in function <SharedXML/Scroll/ScrollBox.lua:608>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:143: in function <SharedXML/CallbackRegistry.lua:142>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:146: in function `TriggerEvent'
...
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2661: in function `EJ_ContentTab_Select'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2621: in function `EJ_ContentTab_OnClick'
[string "*Blizzard_EncounterJournal.xml:1400_OnClick"]:1: in function <[string "*Blizzard_EncounterJournal.xml:1400_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "@Details/functions/boss.lua"]:554: in function <Details/functions/boss.lua:529>
[string "=[C]"]: in function `pcall'
[string "@Details/startup.lua"]:583: in function <Details/startup.lua:11>
[string "=[C]"]: ?
[string "=[C]"]: in function `StartMeUp'
[string "@Details/core/parser.lua"]:6115: in function <Details/core/parser.lua:6114>

Locals:
self = <table> {
 worldBosses = <table> {
 }
 RequestWarfrontInfo = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:94
 GetWorldBossLockout = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:195
 UpdateSavedInstances = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:236
 GetInstanceLockout = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:146
 GetSavedWorldBossEncounterInfo = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:132
 statusFrames = <table> {
 }
 CreateStatusFrame = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:257
 GetSavedWorldBossInfo = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:103
 UpdateInstanceStatusFrame = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:337
 UpdateStatusFramePosition = <function> defined @AdventureGuideLockouts/AdventureGuideLockouts.lua:325
}
button = Button {
 0 = <userdata>
 heroicIcon = EncounterJournalInstanceSelectHeroicIcon {
 }
 link = "|cff66bbff|Hjournal:0:1205:14|h[Dracheninseln]|h|r"
 tooltipText = "Einst war der Himmel der Dracheninseln erfüllt von den Drachen der fünf Schwärme. Doch vor Tausenden von Jahren brachen sie auf, um Azeroth zu verteidigen. Vor Kurzem sind die Inseln jedoch erwacht und riefen nach ihren lange abwesenden Hütern. Sie sollten zurückkehren. Sie waren nicht allein. Vier große Drachen aus der Urzeit kamen auch: Basrikron, Gebieter über Erde und Schiefer; Strunraan, Meister der elektrischen Sturmwinde; Bazual, Manipulator der Flammen, und Liskanoth, Herrin von Eis und Kälte."
 range = EncounterJournalInstanceSelectRange {
 }
 tooltipTitle = "Dracheninseln"
 instanceID = 1205
 SetOrderIndex = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:81
 bgImage = EncounterJournalInstanceSelectbgImage {
 }
 ElementDataMatches = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:72
 GetOrderIndex = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:77
 ModifiedInstanceIcon = Button {
 }
 name = EncounterJournalInstanceSelectName {
 }
 GetElementData = <function> defined @SharedXML/Scroll/ScrollBoxListView.lua:68
}
orderIndex = 1
elementData = <table> {
 instanceID = 1205
 mapID = 2574
 name = "Dracheninseln"
 link = "|cff66bbff|Hjournal:0:1205:14|h[Dracheninseln]|h|r"
 buttonImage = 4742925
 description = "Einst war der Himmel der Dracheninseln erfüllt von den Drachen der fünf Schwärme. Doch vor Tausenden von Jahren brachen sie auf, um Azeroth zu verteidigen. Vor Kurzem sind die Inseln jedoch erwacht und riefen nach ihren lange abwesenden Hütern. Sie sollten zurückkehren. Sie waren nicht allein. Vier große Drachen aus der Urzeit kamen auch: Basrikron, Gebieter über Erde und Schiefer; Strunraan, Meister der elektrischen Sturmwinde; Bazual, Manipulator der Flammen, und Liskanoth, Herrin von Eis und Kälte."
}
(*temporary) = nil
(*temporary) = 2574
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'instanceLockouts' (a nil value)"

happens with 1.4.4

**Comment by Meivyn** [comment]
Would you mind telling exactly what you did when this error happened? It seems to be triggered by Details, but I didn't have this issue myself. It's rather easy to fix but I would like to be able to reproduce before doing so.

**Comment by yoshimo** [comment]
Not exactly, i was plagued with lua errors doing heroic and mythic dungeons last night and afterwards i found herorotation and AGL as well as Memoria in the bugsack log.

**Comment by Meivyn** [comment]
> [string "@Details/functions/boss.lua"]:554: in function <Details/functions/boss.lua:529>

This line doesn't exist in the latest version of Details. Please make sure all your add-ons are updated. Tell me if you still have an issue after updating Details. I will keep this open for now.

**Comment by Darkion43** [comment]
hi ...i have the same problem just now...but it start when i mouseover on scrollbar ( photo) to pick a sound for WIM addon.
![e22e](https://user-images.githubusercontent.com/117835316/209448006-5594a865-982c-46f4-87ea-0bfeaabf80e4.PNG)

so after that i mess around by mouseover on that scrollbar and alot of errors popup ( wim errors) . 
after reload ( to clear errors), attempt to index field 'instanceLockouts' (a nil value) pop up !!!

but is not WIM problem...i try to disable it or even to clear WTF file for that addon but nothing....

EDIT: yes when you disable Details, is ok , no errors...but why ??? i dont even touch Details...:/ ( last update even last alpha)

**Comment by Meivyn** [comment]
> EDIT: yes when you disable Details, is ok , no errors...but why ??? i dont even touch Details...:/ ( last update even last alpha)

Can you provide the full error please? It seems to be an issue that happens only with the Alpha version of Details. Also please give me the exact version of Details that you have.

**Comment by Meivyn** [comment]
It seems that Details is now caching the whole data of the Encounter Journal for some reason (https://github.com/Tercioo/Details-Damage-Meter/commit/eef2d19cefa53154b5267f974717d99bb51d675c). 

I don't know why it does that, but considering the number of people that use Details, if they release this as-is, I will push a fix.

**Comment by Darkion43** [comment]
[Lua 722.txt](https://github.com/Meivyn/AdventureGuideLockouts/files/10299145/Lua.722.txt)
![gg5442](https://user-images.githubusercontent.com/117835316/209451217-4eba42e8-0418-4330-aa4a-a44124433be5.PNG)

 you be able to reproduce the error ??

the weird thing is that I update details, HOURS before the error popup and like i say before, i dont touch Details.

i dont know much about how LUA-XML works but it got my attention, what error say: 
[string "@SharedXML/Scroll/ScrollBox.lua"]:609: in function <SharedXML/Scroll/ScrollBox.lua:608>

this is why I assuming that has something to do (i mean what actual trigger it) with scrollbar I mentioned before.

sorry my eng is bad :P
