### ISSUE TITLE
Discord / user OpenSTDL banned ?

### ISSUE THREAD

**Issue by zDEFz** [Meivyn/AdventureGuideLockouts#25]
Excuse my rudeness. I've noticed that OpenSTDL and all the repos are no more available, including user. Everything appears to be wiped. 
The Discord invite for Crunchy does not work either.

Can you clarify on what happened, and maybe put some more adequate contact option?

Thanks.

**Comment by Meivyn** [comment]
Sorry but I don't have more info than you.
