### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Oschikowski** [Meivyn/AdventureGuideLockouts#3]
Hi,
i use the German WoW Client. And the Addon currently does not working at all. I have no flags displayed in the adventure compendium. For me i can´t find ingame any change from the addon. It looks the same as without the addon :(

Best regards

Osch

![wowscrnshot_082618_195135](https://user-images.githubusercontent.com/42720114/44631255-cf564d80-a969-11e8-8e31-67ddeecaca5f.jpg)

**Comment by Meivyn** [comment]
Can you update to [v1.1.5](https://github.com/Meivyn/EncounterJournalSavedInstances/releases/tag/v1.1.5) and tell me if it's working? I just fixed a major issue with locales that caused the addon to crash. See https://github.com/Meivyn/EncounterJournalSavedInstances/issues/2#issuecomment-416052623

**Comment by Oschikowski** [comment]
Hi,

now it almost works perfect. Just one dungeon still has no flag symbol. (I have id on all the mythic dungeons).

![wowscrnshot_082618_210039](https://user-images.githubusercontent.com/42720114/44631932-3debd900-a973-11e8-814e-ef7e2908e6a8.jpg)

Thanks for the fast reply. Maybe you can "fix" the last small problem.

Thanks a lot.

**Comment by Meivyn** [comment]
Just fixed in 6d2d0d146a901b2d1a6957c678654d5ed6a7a0e6.

**Comment by Oschikowski** [comment]
Thank you so much :)
