### ISSUE TITLE
Italian Locale

### ISSUE THREAD

**Issue by z0fa** [Meivyn/AdventureGuideLockouts#4]
> local L = {
	["Ahn'Qiraj Temple"] = "Tempio di Ahn'qiraj",
	["Assault on Violet Hold"] = "Assalto alla Fortezza Violacea",
	["Auchindoun: Auchenai Crypts"] = "Auchindoun: Cripte degli Auchenai",
	["Auchindoun: Mana-Tombs"] = "Auchindoun: Tombe del Mana",
	["Auchindoun: Sethekk Halls"] = "Auchindoun: Sale dei Sethekk",
	["Auchindoun: Shadow Labyrinth"] = "Auchindoun: Labirinto delle Ombre",
	["August Celestials"] = "Venerabili Celestiali",
	["Available"] = "Disponibile",
	["Black Temple"] = "Tempio Nero",
	["Coilfang: Serpentshrine Cavern"] = "Spiraguzza: Caverna di Sacrespire",
	["Coilfang: The Slave Pens"] = "Spiraguzza: Fosse degli Schiavi",
	["Coilfang: The Steamvault"] = "Spiraguzza: Antro dei Vapori",
	["Coilfang: The Underbog"] = "Spiraguzza: Torbiera Sotterranea",
	["Deadmines"] = "Miniere della Morte",
	["Defeated"] = "Sconfitto",
	["Hellfire Citadel: Ramparts"] = "Cittadella del Fuoco Infernale: Bastioni del Fuoco Infernale",
	["Hellfire Citadel: The Blood Furnace"] = "Cittadella del Fuoco Infernale: Forgia del Sangue",
	["Hellfire Citadel: The Shattered Halls"] = "Cittadella del Fuoco Infernale: Sale della Devastazione",
	["King's Rest"] = "Requie dei Re",
	["Magister's Terrace"] = "Terrazza dei Magisteri",
	["Opening of the Dark Portal"] = "L'apertura del Portale Oscuro",
	["Shrine of the Storm"] = "Santuario della Tempesta",
	["Siege of Boralus"] = "Assedio di Boralus",
	["Tempest Keep"] = "Forte Tempesta",
	["Tempest Keep: The Arcatraz"] = "Forte Tempesta: Arcatraz",
	["Tempest Keep: The Botanica"] = "Forte Tempesta: Botanica",
	["Tempest Keep: The Mechanar"] = "Forte Tempesta: Mechanar",
	["Temple of Sethraliss"] = "Tempio di Sethraliss",
	["The Escape from Durnholde"] = "Fuga da Durnholde",
	["The Sunwell"] = "Cittadella del Pozzo Solare",
	["The Underrot"] = "Grottamarcia",
	["Violet Hold"] = "Fortezza Violacea",
	["Waycrest Manor"] = "Maniero dei Crestabianca",
	["World Bosses"] = "Boss Mondiali"
}

**Comment by Meivyn** [comment]
Thanks for your translation. 

> IMPORTANT: You must run /dump GetInstanceInfo() in your chat while in this specific instance to translate in your current locale. The value I want is the EXACT string at [1] without quotes

Be sure you does this to translate. Also, which of these instances don't work in your locale? Some strings are used only in certain locales to debug them.

**Comment by z0fa** [comment]
> local L = {
["Ahn'Qiraj Temple"] = "Tempio di Ahn'qiraj",
["Assault on Violet Hold"] = "Assalto alla Fortezza Violacea",
["Auchindoun: Auchenai Crypts"] = "Cripte degli Auchenai",
["Auchindoun: Mana-Tombs"] = "Tombe del Mana",
["Auchindoun: Sethekk Halls"] = "Sale dei Sethekk",
["Auchindoun: Shadow Labyrinth"] = "Labirinto delle Ombre",
["August Celestials"] = "Venerabili Celestiali",
["Available"] = BOSS_ALIVE, -- "Disponibile"
["Black Temple"] = "Tempio Nero",
["Coilfang: Serpentshrine Cavern"] = "Caverna di Sacrespire",
["Coilfang: The Slave Pens"] = "Fosse degli Schiavi",
["Coilfang: The Steamvault"] = "Antro dei Vapori",
["Coilfang: The Underbog"] = "Torbiera Sotterranea",
["Deadmines"] = "Miniere della Morte",
["Defeated"] = BOSS_DEAD, -- "Sconfitto"
["Hellfire Citadel: Ramparts"] = "Bastioni del Fuoco Infernale",
["Hellfire Citadel: The Blood Furnace"] = "Forgia del Sangue",
["Hellfire Citadel: The Shattered Halls"] = "Sale della Devastazione",
["King's Rest"] = "Requie dei Re",
["Magister's Terrace"] = "Terrazza dei Magisteri",
["Opening of the Dark Portal"] = "Palude Nera",
["Shrine of the Storm"] = "Santuario della Tempesta",
["Siege of Boralus"] = "Assedio di Boralus",
["Tempest Keep"] = "Occhio della Tempesta",
["Tempest Keep: The Arcatraz"] = "Arcatraz",
["Tempest Keep: The Botanica"] = "Botanica",
["Tempest Keep: The Mechanar"] = "Mecanar",
["Temple of Sethraliss"] = "Tempio di Sethraliss",
["The Escape from Durnholde"] = "Fuga da Durnholde",
["The Sunwell"] = "Cittadella del Pozzo Solare",
["The Underrot"] = "Grottamarcia",
["Violet Hold"] = "Fortezza Violacea",
["Waycrest Manor"] = "Maniero dei Crestabianca",
["World Bosses"] = "Boss Mondiali"
}

> IMPORTANT: You must run /dump GetInstanceInfo() in your chat while in this specific instance to translate in your current locale. The value I want is the EXACT string at [1] without quotes

I have updated the translation using GetInstanceInfo().

> Also, which of these instances don't work in your locale? Some strings are used only in certain locales to debug them.

Strings for BfA instances are working fine, i haven't tested the instances from previous expansions.

**Comment by Meivyn** [comment]
I'll use these translations to debug once they are reported. Thanks for your help.

**Comment by z0fa** [comment]
Okay thanks, for now the only strings that need a translation are these:
> ["Available"] = BOSS_ALIVE, -- "Disponibile"
["Defeated"] = BOSS_DEAD, -- "Sconfitto"

**Comment by Meivyn** [comment]
Didn't know of these global variables, thanks for the tip.

Changed my loop to use these globals:

```LUA
	for i, boss in ipairs(info.bosses) do
		if boss.isKilled then
			GameTooltip:AddDoubleLine(boss.name, BOSS_DEAD, HIGHLIGHT_FONT_COLOR.r, HIGHLIGHT_FONT_COLOR.g, HIGHLIGHT_FONT_COLOR.b, RED_FONT_COLOR.r, RED_FONT_COLOR.g, RED_FONT_COLOR.b)
		elseif not info.complete and not boss.isKilled then
			GameTooltip:AddDoubleLine(boss.name, BOSS_ALIVE, HIGHLIGHT_FONT_COLOR.r, HIGHLIGHT_FONT_COLOR.g, HIGHLIGHT_FONT_COLOR.b, GREEN_FONT_COLOR.r, GREEN_FONT_COLOR.g, GREEN_FONT_COLOR.b)
		end
	end
```

**Comment by z0fa** [comment]
Awesome 😀 , you can find more of them here: https://github.com/tekkub/wow-globalstrings/tree/master/GlobalStrings

**Comment by Meivyn** [comment]
Found this: https://www.townlong-yak.com/framexml/live/GlobalStrings.lua
Much more up to date. I'll use some of them, then push an update later this day. Thanks.

**Comment by Meivyn** [comment]
Release is live. Added some of your strings in 96fbacc47c8ad794625e147ee071a4373476dca7. Thanks for your contribution.
