### ISSUE TITLE
Missing defeat skull icon

### ISSUE THREAD

**Issue by Mystream90** [Meivyn/AdventureGuideLockouts#8]
Hi,
I already post it on curseforge and you want me to post it here to understand it better.

http://prntscr.com/l038i0
On this screenshot you can see I defeated all bosses on normal.

http://prntscr.com/l038t0
http://prntscr.com/l038vh
On these two screenshots you can see those skulls behind the bosses if they defeated.
So behind Zek'vor, Zul and Mythrax are not these Skulls.

Can you fix this?

**Comment by Meivyn** [comment]
Based on your screenshots, you're also using [EncounterJournalPlus_InstanceInfo](https://wow.curseforge.com/projects/encounterjournalplus_instanceinf?gameCategorySlug=addons&projectID=102445) which shows that skull next to defeated bosses as well as the difficulty names and the text on the lower right corner of the journal.

This feature isn't related to my addon. Mine shows flags and their tooltip on instances button.
